# Generated by Django 5.0.1 on 2024-01-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blanket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='blankets/')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(default=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='dresses/')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(default=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('preference', models.CharField(choices=[('Tous', 'Tous'), ('Couvertures', 'Couvertures'), ('Robes', 'Robes')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.blanket')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dress')),
            ],
        ),
    ]
