# Generated by Django 5.0.1 on 2024-01-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
