# Generated by Django 5.0.1 on 2024-01-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='category',
            field=models.CharField(max_length=60),
        ),
    ]
