# Generated by Django 5.0.1 on 2024-02-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_image_productimage_extra_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bottomcategory',
            index=models.Index(fields=['name'], name='products_bo_name_ea19d6_idx'),
        ),
        migrations.AddIndex(
            model_name='midcategory',
            index=models.Index(fields=['name'], name='products_mi_name_6fdaad_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='products_pr_id_b46934_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['top_category'], name='products_pr_top_cat_99a87b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['mid_category_id'], name='products_pr_mid_cat_b94ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'top_category', 'mid_category', 'bottom_category'], name='products_pr_name_b63ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='topcategory',
            index=models.Index(fields=['name'], name='products_to_name_ac706f_idx'),
        ),
    ]
